{
 "title": "Monitor Dashboards",
 "time": { "from": "2023-07-22T07:00:54.070Z", "to": "2023-07-31T17:32:17.602Z" },
 "panels": [
  {
   "title": "Average Drift Score and Missing Value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(drift_score), time_stamp FROM monitor_log GROUP BY time_stamp LIMIT 50 "
    },
    {
     "rawSql": "SELECT time_stamp, AVG(missing_val) FROM monitor_log GROUP BY time_stamp LIMIT 50 "
    }
   ]
  },
  {
   "title": "Request Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(prediction), datestamp FROM user_log GROUP BY datestamp LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share Drift Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT AVG(share_drift), time_stamp FROM monitor_log GROUP BY time_stamp LIMIT 50 "
    }
   ]
  },
  {
   "title": "Drift Column Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT time_stamp, MAX(drift_col) FROM monitor_log GROUP BY time_stamp LIMIT 50 "
    }
   ]
  }
 ]
}