version: "3.9"

networks:
  back-tier:
  front-tier:
  
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASS_DB}
    volumes:
      - ${VOLUMN_PATH}:/var/lib/postgresql/data
    networks:
      - back-tier
    profiles: ["mlflow"]


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - back-tier
    profiles: ["mlflow"]

  mlserver:
    restart: always
    image: mlflow
    depends_on:
        - db
    ports:
        - "5000:5000"    
    networks:
        - back-tier 

    command: mlflow server --host 0.0.0.0 --backend-store-uri postgresql://${USER_DB}:${PASS_DB}@db:5432/${DB_NAME} --default-artifact-root s3://${S3_BUCKET}
    profiles: ["mlflow"]
  
  webapp:
    restart: always
    image: webapp
    ports:
        - "9696:9696"  
    networks:
      - front-tier
    environment:
        - AWS_ACCESS_KEY_ID=${ACCESS_KEY}
        - AWS_SECRET_ACCESS_KEY=${ACCESS_SCRECT}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - RUN_ID=${RUN_ID}
        - S3_BUCKET=${S3_BUCKET}
        - EXPERIMENT_ID=${EXPERIMENT_ID}
    command: waitress-serve --host 0.0.0.0 --port 9696 predict:app
    profiles: ["webapp"]
    
  # grafana:
  #   image: grafana/grafana
  #   user: "472"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
  #     - ./config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
  #     - ./dashboards:/opt/grafana/dashboards
  #   networks:
  #     - back-tier
  #     - front-tier
  #   restart: always